/* eslint-disable no-restricted-globals */

// This service worker uses the Workbox CDN for maximum compatibility with CRA without ejecting.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/6.4.1/workbox-sw.js');

if (workbox) {
    console.log('Workbox is loaded');

    const { clientsClaim } = workbox.core;
    const { ExpirationPlugin } = workbox.expiration;
    const { precacheAndRoute, createHandlerBoundToURL } = workbox.precaching;
    const { registerRoute, NavigationRoute } = workbox.routing;
    const { StaleWhileRevalidate, NetworkOnly } = workbox.strategies;

    clientsClaim();

    // Precache all of the assets generated by your build process.
    // The injection point for the manifest:
    precacheAndRoute(self.__WB_MANIFEST || []);

    // App Shell routing
    const handler = createHandlerBoundToURL('/index.html');
    const navigationRoute = new NavigationRoute(handler, {
        denylist: [/^\/_/, /\/[^/?]+\.[^/]+$/],
    });
    registerRoute(navigationRoute);

    // Runtime caching for images
    registerRoute(
        ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'),
        new StaleWhileRevalidate({
            cacheName: 'images',
            plugins: [
                new ExpirationPlugin({ maxEntries: 50 }),
            ],
        })
    );

    // Offline fallback
    const offlineFallbackPage = '/offline.html';
    // We precache the offline page in the build script.

    self.addEventListener('install', (event) => {
        event.waitUntil(
            caches.open('offline').then((cache) => cache.add(offlineFallbackPage))
        );
    });

    registerRoute(
        ({ request }) => request.mode === 'navigate',
        ({ event }) => {
            return workbox.strategies.networkFirst().handle({ event }).catch(() => {
                return caches.match(offlineFallbackPage);
            });
        }
    );

    // skipWaiting logic
    self.addEventListener('message', (event) => {
        if (event.data && event.data.type === 'SKIP_WAITING') {
            self.skipWaiting();
        }
    });
}
